acoont/urls.py
from django.urls import path
from . import views

app_name = 'acoont'
urlpatterns = [
    path('register', views.registerViwe.as_view(), name='register'),
    path('check', views.checkotpViwe.as_view(), name='check_otp'),
    path('logout', views.logout_user, name='logout'),
    path('login', views.User_Login.as_view(), name='login'),

]

eshtrak/urls.py
from django.contrib import admin
from django.urls import path
from . import views


admin.autodiscover()

urlpatterns = [
    path('eshtrakDay', views.eshtrakDay.as_view(), name='eshtrak7'),
    path('eshtrakWeek', views.eshtrakWeek.as_view(), name='eshtrakWeek'),
    path('eshtrakMonth', views.eshtrakMonth.as_view(), name='eshtrakMonth'),
    path('eshtrak3Month', views.eshtrak3Month.as_view(), name='eshtrak3Month'),
    path('del', views.delMi.as_view(), name='delmi'),
    path('nemodar', views.rezapanel.as_view(), name='nemodar'),
]

film/urls.py
from django.urls import path, re_path

from . import views

appname = 'Film'
urlpatterns = [
    path('learning', views.FilmView.as_view(), name='learning'),
    re_path(r'learning/(?P<slug>[-\w]+)$', views.DitaylFilm.as_view(), name='DitaylFilm'),

]

panel/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [

    path('panel', views.PanelView.as_view(), name='admin')

]

roman/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('marmar/', admin.site.urls),
      path('', include('home.urls')),
      path('', include('post.urls')),
      path('', include('acoont.urls')),
      path('', include('eshtrak.urls')),
      path('', include('panel.urls')),
      path('', include('prof.urls')),
      path('', include('forum.urls')),
      path('', include('film.urls')),
      path('', include('bookapi.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshtrak/models.py
from django.db import models
from django.utils import timezone
from acoont.models import User
from post.models import post



class tkfifcode(models.Model):
    name = models.CharField(max_length=30, verbose_name='کد تخفیف', unique=True)
    darsad = models.SmallIntegerField(default=0, verbose_name='درصد کد تخفیف')
    tedad = models.IntegerField(default=1, verbose_name='تعداد کد تخفیف')

    class Meta:
        verbose_name = 'کد تخفیف'
        verbose_name_plural = 'کد های تخفیف'

    def __str__(self):
        return self.name


class Day1(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    kaymat = models.IntegerField(default=0, verbose_name='قیمت')
    modate = models.CharField(max_length=100, verbose_name="مدت زمان")
    time = models.DateTimeField(default=0, verbose_name='مدت زمان باقی مانده')
    create = models.DateTimeField(auto_now_add=True)

    # time2 = models.IntegerField(default=timezone.datetime.timestamp(timezone.now()))

    class Meta:
        verbose_name = 'شتراک ویژه'
        verbose_name_plural = 'اشتراک های ویژه'


class ssion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    kaymat = models.IntegerField(default=0, verbose_name='قیمت')
    modate = models.CharField(max_length=100, verbose_name="مدت زمان")
    time = models.DateTimeField(default=0, verbose_name='مدت زمان باقی مانده')
    class Meta:
        verbose_name = 'سشن موفقت اشتراک'
        verbose_name_plural = 'اشتراک های ویژه موقت'
        
        
        
        
        
        
class buy(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    roman = models.ForeignKey(post, on_delete=models.CASCADE, verbose_name='رمان')
    Condition = models.BooleanField(default=False, verbose_name='وضعیت خرید')
    many = models.IntegerField(default=0, verbose_name='قیمت')

    class Meta:
        verbose_name = 'خرید تکی'
        verbose_name_plural = "خرید های تکی"

panel/models.py
from django.db import models

# Create your models here.

eshtrak/views.py
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from acoont.models import User
from .models import tkfifcode, Day1, buy
from post.models import post
from django.contrib import messages


class eshtrakDay(View):
    def get(self, request):

        timedel = timezone.datetime.now() + timezone.timedelta(days=1)
        self.request.session['discode1'] = {'user': str(request.user), 'kaymat': int(5000), 'modate': 'یک روزه',
                                            'tiem': str(timedel)}

        self.request.session['milad'] = 5000
        order1 = 'یک روزه 5 هزار '
        order = self.request.session.get('amini', 5000)
        self.request.session.save()
        return render(request, 'eshtrak7.html', {'or': order, 'or2': order1})

    def post(self, request):
        timedel = timezone.datetime.now() + timezone.timedelta(days=1)
        code_t = self.request.session['milad']
        code = request.POST.get('code')
        t_code = tkfifcode.objects.all().first()
        if code == str(t_code):
            dis = get_object_or_404(tkfifcode, name=code)
            code_t -= code_t * dis.darsad / 100
            dis.tedad -= 1
            dis.save()
            self.request.session['discode'] = {'user': str(request.user), 'kaymat': int(code_t), 'modate': 'یک روزه',
                                               'tiem': str(timedel)}
            self.request.session['amini'] = int(code_t)
            self.request.session.modified = True
            return redirect(request.path_info)
        else:
            mimi = tkfifcode.objects.first()
            erroe = True
            self.request.session['milad'] = 5000
            order1 = 'یک روزه 5 هزار'
            order = self.request.session.get('amini', 5000)
            self.request.session.save()
            return render(request, 'eshtrak7.html', {'or': order, 'or2': order1, 'mimi': mimi, 'er': erroe})


class eshtrakWeek(View):
    def get(self, request):

        timedel = timezone.datetime.now() + timezone.timedelta(days=7)
        self.request.session['discode1'] = {'user': str(request.user), 'kaymat': int(30000), 'modate': 'یک هفته',
                                            'tiem': str(timedel)}

        self.request.session['milad'] = 30000
        order1 = 'یک هفته 30 هزار'
        order = self.request.session.get('amini', 30000)
        self.request.session.save()
        return render(request, 'eshtrak7.html', {'or': order, 'or2': order1})

    def post(self, request):
        timedel = timezone.datetime.now() + timezone.timedelta(days=7)
        code_t = self.request.session['milad']
        code = request.POST.get('code')
        t_code = tkfifcode.objects.all().first()
        if code == str(t_code):
            dis = get_object_or_404(tkfifcode, name=code)
            code_t -= code_t * dis.darsad / 100
            dis.tedad -= 1
            dis.save()
            self.request.session['discode'] = {'user': str(request.user), 'kaymat': int(code_t), 'modate': 'یک هفته',
                                               'tiem': str(timedel)}
            self.request.session['amini'] = int(code_t)
            self.request.session.modified = True
            return redirect(request.path_info)
        else:
            mimi = tkfifcode.objects.first()
            erroe = True
            self.request.session['milad'] = 30000
            order1 = 'یک هفته 30 هزار'
            order = self.request.session.get('amini', 30000)
            self.request.session.save()
            return render(request, 'eshtrak7.html', {'or': order, 'or2': order1, 'mimi': mimi, 'er': erroe})


class eshtrakMonth(View):
    def get(self, request):

        timedel = timezone.datetime.now() + timezone.timedelta(days=30)
        self.request.session['discode1'] = {'user': str(request.user), 'kaymat': int(100000), 'modate': 'یک ماهه',
                                            'tiem': str(timedel)}

        self.request.session['milad'] = 100000
        order1 = 'یک ماهه 100 هزار'
        order = self.request.session.get('amini', 100000)
        self.request.session.save()
        return render(request, 'eshtrak7.html', {'or': order, 'or2': order1})

    def post(self, request):
        timedel = timezone.datetime.now() + timezone.timedelta(days=30)
        code_t = self.request.session['milad']
        code = request.POST.get('code')
        t_code = tkfifcode.objects.all().first()
        if code == str(t_code):
            dis = get_object_or_404(tkfifcode, name=code)
            code_t -= code_t * dis.darsad / 100
            dis.tedad -= 1
            dis.save()
            self.request.session['discode'] = {'user': str(request.user), 'kaymat': int(code_t), 'modate': 'یک ماهه',
                                               'tiem': str(timedel)}
            self.request.session['amini'] = int(code_t)
            self.request.session.modified = True
            return redirect(request.path_info)
        else:
            mimi = tkfifcode.objects.first()
            erroe = True
            self.request.session['milad'] = 100000
            order1 = 'یک ماهه 100 هزار'
            order = self.request.session.get('amini', 100000)
            self.request.session.save()
            return render(request, 'eshtrak7.html', {'or': order, 'or2': order1, 'mimi': mimi, 'er': erroe})


class eshtrak3Month(View):
    def get(self, request):

        mimi = tkfifcode.objects.first()
        timedel = timezone.datetime.now() + timezone.timedelta(days=120)
        self.request.session['discode1'] = {'user': str(request.user), 'kaymat': int(240000), 'modate': 'سه ماهه',
                                            'tiem': str(timedel)}

        self.request.session['milad'] = 240000
        order1 = 'سه ماهه 240 هزار'
        order = self.request.session.get('amini', 240000)
        self.request.session.save()
        return render(request, 'eshtrak7.html', {'or': order, 'or2': order1, 'mimi': mimi})

    def post(self, request):
        timedel = timezone.datetime.now() + timezone.timedelta(days=120)
        code_t = self.request.session['milad']
        code = request.POST.get('code')
        t_code = tkfifcode.objects.all().first()
        if code == str(t_code):
            dis = get_object_or_404(tkfifcode, name=code)
            code_t -= code_t * dis.darsad / 100
            dis.tedad -= 1
            dis.save()
            self.request.session['discode'] = {'user': str(request.user), 'kaymat': int(code_t), 'modate': 'سه ماهه',
                                               'tiem': str(timedel)}
            self.request.session['amini'] = int(code_t)
            self.request.session.modified = True
            return redirect(request.path_info)
        else:
            mimi = tkfifcode.objects.first()
            erroe = True
            self.request.session['milad'] = 240000
            order1 = 'سه ماهه 240 هزار'
            order = self.request.session.get('amini', 240000)
            self.request.session.save()
            return render(request, 'eshtrak7.html', {'or': order, 'or2': order1, 'mimi': mimi, 'er': erroe})


class delMi(View):
    def get(self, requset):
        mi = Day1.objects.filter(user=requset.user)
        userr = User.objects.filter(phone=requset.user.phone).first()
        userr.eshtrak = False
        userr.save()
        mi.delete()
        return redirect('/')


class rezapanel(View):
    def get(self, request):
        pos = Day1.objects.all()
        amini = pos.time - timezone.timedelta(days=7)
        for milad in pos:
            print(milad.time)
            print(milad.time - timezone.timedelta(days=7))
        b = buy.objects.all()
        return render(request, 'nemodar.html', {'post': pos, 'b': b})

panel/views.py
from django.shortcuts import render, redirect
from django.views import View
from post.models import post, Podcast
from acoont.models import User
from django.db.models import Sum
from eshtrak.models import Day1, buy


# Create your views here.


class PanelView(View):
    def get(self, request):
        us = User.objects.count()
        blok = User.objects.filter(blok=True).count()
        vi = post.objects.aggregate(Sum('view'))['view__sum']
        rom = post.objects.all().count()
        P_vi = Podcast.objects.aggregate(Sum('view'))['view__sum']
        pod = Podcast.objects.all().count()
        roman_name = post.objects.all()
        esh = Day1.objects.all().count()
        bu = buy.objects.all().count()

        if request.user.is_authenticated:
            if request.user.is_admin == True:
                return render(request, 'panel.html',
                              {'user': us, 'blok': blok, 'vi': vi, 'rom': rom, 'P_vi': P_vi, 'pod': pod, 'esh': esh,
                               'buy': bu,
                               'roman_name': roman_name})
            else:
                return redirect(request.path_info)
        else:
            return redirect('acoont:register')

templates/blok.html
{% extends 'base.html' %}{% load static %}
{% block home %}
    <section class="mb-5">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="">
                    <div class="title-box mb-2">

                    </div>
                </div>
                <div class='text-center'>
                    <div class="not-found bg-white rounded border p-3 pb-5">
                        <p>{{ malek.body |safe }}</p>
                        <br>
                        <div class="pt-5 pb-5">

                            <h4>{{ malek.title }}</h4>
                            <br>
                            <h4>{{ malek.name }}</h4>
                            <img class="imgmilad" src="{{ malek.img.url }}" alt="">
                        </div>


                        <div class="miladbox">
                            <H4 class="p-3" style="font-size: 30px; font-weight: bold;">مدیران </H4>
                            {% for item in karbar %}
                                <div class="miladdiv">
                                    <img src="{{ item.img.url }}"
                                         alt=""
                                         style="border-radius: 20%; box-shadow: rgba(0, 0, 0, 0.2) 0px 60px 40px -7px;">
                                    <h4 class="p-3">{{ item.title }}</h4>
                                    <h6 class="" style="font-size: 20px">{{ item.body }}</h6>
                                    <hr>
                                </div>
                            {% endfor %}

                        </div>

                        <div class="search-box px-0 px-md-5 mt-5">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L2W3M8F38X"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'G-L2W3M8F38X');
    </script>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TWRLRJ7"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->


{% endblock home %}

templates/category.html
{% extends 'base.html' %}{% load static %}
{% block title %}
    <title>رمان ها</title>
{% endblock title %}
{% block home %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-wrap p-3 bg-white my-4 rounded">
                    <nav>
                        <ol class="d-flex">

                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <section class="mb-5">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="title-box mb-2">
                        <p class="m-0 p-0">دسته بندی : <span class="text-primary">رمان</span></p>
                    </div>
                </div>
                {% for item in post %}
                    <div class="col-sm-6 col-md-6 col-lg-4 my-3">
                        <div class="blg-wrap bg-white pb-3">
                            <figure class="position-relative">
                                <img src="{{ item.img.url }}" alt="" class="w-100">
                                <figcaption class="position-absolute w-100 h-100"><span
                                        class="blg-dt">{{ item.created }}</span>
                                </figcaption>
                            </figure class="position-relative">
                            <div class="px-3 py-1 text-start">
                                <span class="blg-cat-name d-inline-block bg-info py-1 px-2">مطالب روز</span>
                            </div>
                            <a href="#">
                                <h4 class="blg-title p-3 mx-5 text-dark border-bottom overflow-hidden">{{ item.title }}</h4>
                            </a>
                            <div class="post-type d-flex p-3 pb-0">
                                <i class="bi bi-card-text d-inline-block text-info text-center"></i>
                                <span>رمان</span>
                            </div>
                            <p class="p-4 overflow-hidden">{{ item.body }} </p>
                        </div>
                        <a href="{% url 'postView' item.slug %}">
                            <button type="button" class="btn btn-primary m-3 btn-slide">دیدن</button>
                        </a>
                    </div>

                {% endfor %}


            </div>
        </div>
    </section>
    <div class="container">
        <div class="row">
            <div class="col-12 mb-5">
                <div class="pagination-wrap">

                   {% if post.has_other_pages %}
                        <ul class="d-flex justify-content-center">


                            {% if post.has_previous %}
                                <li><a href="?page={{ post.previous_page_number }}"><<</a></li>
                            {% endif %}

                            {% for i in post.paginator.page_range %}
                                {% if post.number == i %}
                                    <li class="active"><a href="?page={{ i }}">{{ i }}</a></li>
                                {% else %}
                                    <!--<li><a href="?page={{ i }}">{{ i }}</a></li>-->
                                {% endif %}
                            {% endfor %}

                            {% if post.has_next %}
                                <li><a href="?page={{ post.next_page_number }}">>></a></li>
                            {% endif %}
                        </ul>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

    </div>
    
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-L2W3M8F38X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-L2W3M8F38X');
</script>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TWRLRJ7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

{% endblock home %}

templates/erroremogi.html
{% extends 'base.html' %}{% load static %}
{% block home %}
      <section class="mb-5">
         <div class="container">
            <div class="row justify-content-center align-items-center">
               <div class="col-12">
                  <div class="title-box mb-2">
                     <p class="m-0 p-0"><span class="text-primary">خطا</span></p>
                     <span class="d-block"><a href="{% url 'PodcastView' %}">بازگشت  </a> <i class="bi bi-arrow-left position-relative"></i></span>
                  </div>
               </div>
               <div class="col-md-8 text-center">
                  <div class="not-found bg-white rounded border p-3 pb-5">
                     <span class="my-3 my-md-4">
                    متن نادرستی استفاده کرده اید لطفا متن یا نام خود را به دستی وارد کیند
                     </span>
                     <p class="m-0">از ایموجی ها نمیتوانید استفاده کنید</p>
                     <span class="d-block my-3">بازگشت به <a href="{% url 'PodcastView' %}"> بازگشت</a> سایت</span>
                     <div class="search-box px-0 px-md-5 mt-5">
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>

{% endblock %}

templates/eshtrak7.html
{% extends 'base.html' %}{% load static %}
{% block title %}
    <title>کد تخفیف اشتراک</title>
{% endblock title %}
{% block home %}
    <section class="mb-5">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-12 pt-5 ">
                </div>
                <div class="text-center">
                    <div class="not-found bg-white rounded border p-3 pb-5">
                        <h3>خرید اشتراک ویژه</h3>

                        <div class="row justify-content-center align-items-center">
                            <h4 class="p-3">خرید اشتراک {{ or2 }} تومان </h4>
                            <h4 class="p-3">مبلغ قابل پرداخت {{ or }} تومان</h4>
                        </div>
                        {% if er == True %}
                            <h5 class="alert alert-danger">کد تخفیف وارد شده اشتباه یا منقضی شده میباشد</h5>
                        {% endif %}
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input type="text" name="code" placeholder="کد تخفیف">
                            <button type="submit" class="mt-2">اعمال کردن</button>
                        </form>
                        <h4 class="pt-5">اگر از خرید خود اطمینان دارید روی دکمه خرید کلیک کنید تا به درگاه پرداخت هدایت
                            بشید</h4>
                        <a href="{% url 'sen' %}">
                            <button class="mt-5 w-50">خرید</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/open-book.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEN BOOK</title>

    <link rel="stylesheet" href="{% static 'part/assets/all.css' %}">
    <link rel="stylesheet" href="{% static 'part/assets/css/open.css' %}">
    <!-- script -->
    <script src="{% static 'part/assets/js/open-book.js' %}" defer></script>
    <!-- script -->


</head>

<body>


<div class="book">


    {% for foo in rom %}
        <div class="page" id="page-3">
            <div class="page-body">
                <h4 class="page-title">{{ foo.name }}</h4>
                <p class="page-text">
                    {{ foo.body | safe }}
                </p>
            </div>
            <div class="watermark"><p>bookhut.ir</p></div>
        </div>
    {% endfor %}


</div>
</body>

</html>

templates/rejister.html
{% extends 'base.html' %}{% load static %}
{% block title %}
    <title>ثبت نام</title>
{% endblock title %}
{% block home %}
    <main class="page-wrapper">
        <!-- Page content-->
        <div class="container-fluid d-flex h-100 align-items-center justify-content-center py-4 py-sm-5">
            <div class="card card-body" style="max-width: 940px"><a
                    class="position-absolute top-0 end-0 nav-link fs-sm py-1 px-2 mt-3 me-3" href="#"
                    onclick="window.history.go(-1); return false;"><i class="fi-arrow-long-right fs-base me-2"></i>برگشت</a>
                <div class="row mx-0 align-items-center">
                    <div class="col-md-6 border-end-md p-4 p-sm-5">
                        <h2 class="h3 mb-4 mb-sm-5">در سایت ما با اطمینان ثبت نام کنید.</h2>
                        <ul class="list-unstyled mb-4 mb-sm-5">
                            <li class="d-flex mb-2"><i class="fi-check-circle text-primary mt-1 me-2"></i><span>افزودن و ارتقا آگهی</span>
                            </li>
                            <li class="d-flex mb-2"><i class="fi-check-circle text-primary mt-1 me-2"></i><span>دسترسی به خواندن رمان ها</span>
                            </li>
                            <li class="d-flex mb-0"><i
                                    class="fi-check-circle text-primary mt-1 me-2"></i><span>ثبت نظر</span></li>
                        </ul>
                        <img class="d-block mx-auto rotate-img" src="{% static 'prof/img/signin-modal/signup.svg' %}"
                             width="344" alt="Illustartion">
                        <div class="mt-sm-4 pt-md-3">ثبت نام کرده اید؟ <a href="{% url 'acoont:login' %}">ورود به حساب
                            کاربری</a></div>
                    </div>
                    <div class="col-md-6 px-4 pt-2 pb-4 px-sm-5 pb-sm-5 pt-md-5">
                        {% for error in form.phone.errors %}
                            <div class="alert alert-warning d-flex" role="alert">
                                <i class="fi-alert-triangle me-2 me-sm-3 lead"></i>
                                <div>{{ error }}</div>
                            </div>

                        {% endfor %}
                        {% for error in form.password.errors %}
                            <div class="alert alert-warning d-flex" role="alert">
                                <i class="fi-alert-triangle me-2 me-sm-3 lead"></i>
                                <div>{{ error }}</div>
                            </div>
                        {% endfor %}
                        <div class="d-flex align-items-center py-3 mb-3">


                            <hr class="w-100">
                            <div class="px-3">ثبت</div>
                            <div class="px-3"> نام</div>
                            <hr class="w-100">
                        </div>
                        <form method="post" class="needs-validation" novalidate>
                            {% csrf_token %}
                            <div class="mb-4">
                                <label class="form-label" for="signup-name">نام و نام خانوادگی</label>
                                {{ form.name }}
                            </div>
                            <div class="mb-4">
                                <label class="form-label" for="signup-phone">شماره همراه</label>
                                {{ form.phone }}
                            </div>
                            <div class="mb-4">
                                <label class="form-label" for="signup-password">رمز عبور <span class='fs-sm text-muted'>حداقل 8 کاراکتر</span></label>
                                <div class="password-toggle">
                                    {{ form.password }}
                                    <label class="password-toggle-btn" aria-label="Show/hide password">
                                        <input class="password-toggle-check" type="checkbox"><span
                                            class="password-toggle-indicator"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="mb-4">
                                <label class="form-label" for="signup-password-confirm">تایید رمز عبور</label>
                                <div class="password-toggle">
                                    {{ form.password2 }}
                                    <label class="password-toggle-btn" aria-label="Show/hide password">
                                        <input class="password-toggle-check" type="checkbox"><span
                                            class="password-toggle-indicator"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="form-check mb-4">
                                <input class="form-check-input" type="checkbox" id="agree-to-terms" required>
                                <label class="form-check-label" for="agree-to-terms"> با ثبت نام در این سایت <a
                                        href=''> شرایط</a> و <a href=''>قوانین </a> سایت را قبول دارم.</label>
                            </div>
                            <button class="btn btn-primary btn-lg w-100" type="submit">ثبت نام</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock home %}

templates/submited.html
{% extends 'base.html' %}{% load static %}
{% block home %}
      <section class="mb-5">
         <div class="container">
            <div class="row justify-content-center align-items-center">
               <div class="col-12">
                  <div class="title-box mb-2">
                     <p class="m-0 p-0"><span class="text-primary">خطا</span></p>
                     <span class="d-block"><a href="{% url 'homeView' %}">بازگشت به صفحه اصلی</a> <i class="bi bi-arrow-left position-relative"></i></span>
                  </div>
               </div>
               <div class="col-md-8 text-center">
                  <div class="not-found bg-white rounded border p-3 pb-5">
                     <span class="my-3 my-md-4">
                    خرید شما موفقیت امیز نبود
                     </span>
                     <p class="m-0">استاتوس کد دریافتی  {{ status }} </p>
                     <span class="d-block my-3">بازگشت به <a href="{% url 'homeView' %}">صفحه اصلی</a> سایت</span>
                     <div class="search-box px-0 px-md-5 mt-5">
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>

{% endblock %}